name: sdk-py-provider-alldata
version: 2.5.0
summary: ctrlX Data Layer provider sample in Python
title: sdk-py-provider-alldata
description: |
  ctrlX Data Layer provider in Python publishing nodes of all data types
base: core22
confinement: strict
grade: stable

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  provider:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
