# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: ctrlx-dotnet-datalayer-mqtt
version: '1.0.0'
summary: ctrlX Data Layer MQTT sample written in .NET for ctrlX CORE.
description: |
  MQTT sample showing PUB/SUB with ctrlX Data Layer in full interaction.
confinement: strict 
#confinement: devmode 
#icon: assets/icons/ICONHERE.png
grade: stable  # must be 'stable' to release into candidate/stable channels
base: core22
type: app

apps:
  app:
    command: datalayer.mqtt
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs: [network, network-status, network-bind, process-control]
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s

    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'true'
 
parts:
  app:
    plugin: dump
    source: ./publish/${SNAPCRAFT_TARGET_ARCH}

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 