name: sdk-py-remote-debug
version: 3.0.0
summary: ctrlX Data Layer client demonstates remote debugging on a ctrlX
title: sdk-py-remote-debug
description: |
  The sample demonstrates how remote debugging on a ctrlX can be done. 
base: core22
confinement: strict
grade: stable

apps:
  app:
    command: bin/main.py
    plugs:
     - network
     - network-bind
     - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 
      
parts:
  app:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
