# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: rexroth-hello-webserver
version: '2.0.0'
icon: snap/icons/icon.png
summary: Simple Go-Webserver 
description: This sample app shows how to create a webserver app in ctrlX CORE
grade: stable
confinement: strict
base: core22

apps:
  my-server:
    command: ./bin/webserver 
    plugs:
      - network
      - network-bind
      - network-status
      - active-solution
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

parts:
  simple-webserver:
    source: .
    plugin: go
    override-build: |
      case $SNAPCRAFT_ARCH_TRIPLET in
        aarch64-linux-gnu)
          export GOARCH=arm64
          export GOARM=7
          export CGO_ENABLED=0
          GO111MODULE=on
          ;;
        amd64)
          export GOARCH=amd64
          ;;
      esac
      go build -buildvcs=false -o ../install/bin/ ./...
    
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
    
  my-server:
    plugin: dump
    source: ./www
    organize:
      '*' : www/
    
slots:
  # This slot is for sidebar integration
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
      - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
