name: sdk-py-appdata
version: 3.0.0
summary: Application data sample written in Python for ctrlX
title: sdk-py-appdata
description: |
  This sample demonstrates how to persist your application data in ctrlX CORE

base: core22
confinement: strict
grade: stable

apps:
  appdata:
    command: bin/main.py
    plugs:
      - network-bind
      - active-solution
    slots:
      - package-assets
      - package-run
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s 

parts:
  appdata:
    plugin: python
    source: .

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
      - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
